name: "nodiff"
on: pull_request

jobs:
  nodiff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nodiff
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          do-this-in-response: |
            {
              "requestReviewers": ["dabrady", "devtools-p2"],
              "comment": "You made meaningless changes to these:\n%{filesAsMarkdownList}\n\nEnsure you're leaving the code better than you found it!",
              "fail": true
            }
