name: "nodiff"
on: pull_request

jobs:
  nodiff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch base branch
        env:
          BASE: ${{ github['base_ref'] }}
        run: |
          git fetch --no-tags --prune --depth=1 origin \
              +refs/heads/${BASE}:refs/remotes/origin/${BASE}
      - id: nodiff
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          do-this-in-response: |
            {
              "requestReviewers": ["dabrady", "devtools-p2"],
              "comment": "Yo that's no good"
            }
      - run: |
          echo '${{ steps.nodiff.outputs.files }}'
          echo -e "You made meaningless changes to:\n${{ steps.nodiff.outputs.filesAsMarkdownList }}"
        shell: bash
